INSERT INTO TODO(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1551,'tinhxpear','Learn MongoDB', '2025-10-24', false);

INSERT INTO TODO(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1552,'thaipt','Learn MongoDB', '2025-10-24', false);

INSERT INTO TODO(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1553,'duongnt','Learn Selenium', '2025-10-24', false);

INSERT INTO TODO(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1554,'tinhxpear','Learn React JS', '2025-10-24', false);
